#!/usr/bin/env python3
"""Generate a model's six GYRE inlists from its MESA .GYRE profile.

Every window in the inlists follows from the model, the way sec 2 of
Plans/nonlinear-coupling-pipeline.md derived them for dsct_M2.0 by hand:

  nu_dyn   = sqrt(GM/R^3)                 -- sets the detuning cut
  Dnu      = 1 / (2 int dr/c_s)           -- p-mode large separation
  nu_ac    = c_s / (4 pi H_p) at the top  -- acoustic cutoff, caps the p scan
  I        = int (N/r) dr                 -- g-mode asymptotic integral
  K        = I * 86400 / (2 pi^2)         -- omega[c/d] = K sqrt(l(l+1)) / |n|

K is the constant the wide net's per-l n_pg windows are built from.  On
dsct_M2.0 this analytic form gives K = 16.60 against the 16.56 fitted on
summary_probe100.h5 -- 0.25%, which the deliberately-wider 'gnet' scan window
absorbs.

    python3 scripts/make_inlists.py models/dsct_M2.0_T7696 \
        --profile profile255.data.GYRE

The parametric-daughter band defaults to the dsct_M2.0 band (1.7-5.2 c/d)
scaled by nu_dyn.  That is a scaling assumption, not a derivation: the true
band is omega_c/2 over the *direct daughter* frequencies, which are known
only after three_mode_search.py has enumerated triplets for this model.  Re-run with
--daughter-band LO HI once they are, and diff the n_pg windows.
"""

from __future__ import annotations

import argparse
import math
import pathlib

import numpy as np

G = 6.67430e-8
DAY = 86400.0

# dsct_M2.0 reference, for the scaled defaults
REF_NU_DYN = 2.866       # c/d
REF_BAND = (1.7, 5.2)    # c/d, parametric daughters
REF_SCAN_LO = 0.8        # c/d, bottom of the 'core' INVERSE scan
REF_SPLIT = 25.0         # c/d, INVERSE -> LINEAR handover
REF_SCAN_HI = 95.0       # c/d, top of the 'core' LINEAR scan
CORE_N_PG = 20           # |n_pg| for the parent / direct-daughter families


def read_gyre_model(path: pathlib.Path) -> dict:
    """M, R and the three integrals, straight off the GYRE input file."""
    head = path.open().readline().split()
    n, M, R = int(head[0]), float(head[1]), float(head[2])
    a = np.loadtxt(path, skiprows=1)
    r, P, T, rho, N2, G1 = (a[:, 1], a[:, 4], a[:, 5], a[:, 6], a[:, 8], a[:, 9])

    ok = r > 0
    r, P, rho, N2, G1 = r[ok], P[ok], rho[ok], N2[ok], G1[ok]
    cs = np.sqrt(G1 * P / rho)

    nu_dyn = math.sqrt(G * M / R**3) * DAY / (2 * math.pi)
    Dnu = 1.0 / (2.0 * np.trapezoid(1.0 / cs, r)) * DAY          # c/d
    Hp = P[-1] / (rho[-1] * G * M / R**2)
    nu_ac = cs[-1] / (4.0 * math.pi * Hp) * DAY                  # c/d
    Npos = np.sqrt(np.clip(N2, 0.0, None))
    I = np.trapezoid(Npos / r, r)                                # s^-1
    K = I * DAY / (2.0 * math.pi**2)                             # c/d

    return dict(n=n, M=M, R=R, nu_dyn=nu_dyn, Dnu=Dnu, nu_ac=nu_ac, I=I, K=K)


def gnet_windows(K: float, band: tuple[float, float], l_lo: int, l_hi: int,
                 floor_l: int, floor_n: int) -> dict[int, tuple[int, int]]:
    """|n| in [K*Lam/hi, K*Lam/lo] per l, as (n_pg_min, n_pg_max), both < 0."""
    lo, hi = band
    out = {}
    for l in range(l_lo, l_hi + 1):
        Lam = math.sqrt(l * (l + 1))
        n_min = math.ceil(K * Lam / hi)     # shallowest, highest frequency
        n_max = math.floor(K * Lam / lo)    # deepest, lowest frequency
        if l <= floor_l:
            n_min = max(n_min, floor_n)     # 'core' already covers shallower
        if n_max < n_min:
            continue
        out[l] = (-n_max, -n_min)
    return out


def mode_block(l: int, n_lo: int, n_hi: int, tag: str) -> str:
    return (f"\n&mode\n  l = {l}\n  n_pg_min = {n_lo}\n  n_pg_max = {n_hi}\n"
            f"  tag = '{tag}'\n/\n")


HEADER = """! GENERATED by scripts/make_inlists.py -- edit that, not this.
!
! Model: {model}   M = {M_msun:.3f} Msun   R = {R_rsun:.4f} Rsun
!   sqrt(GM/R^3) = {nu_dyn:.4f} c/d        detuning cut 0.15*nu_dyn = {cut:.4f} c/d
!   large separation Dnu = {Dnu:.3f} c/d   acoustic cutoff = {nu_ac:.1f} c/d
!   int(N/r)dr = {I:.4e} s^-1              K = {K:.3f} c/d  (omega = K*Lam/|n|)
"""


def write(path: pathlib.Path, text: str, force: bool) -> None:
    if path.exists() and not force:
        raise SystemExit(f"refusing to overwrite {path} (pass --force)")
    path.write_text(text)
    print(f"  wrote {path}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("model_dir", type=pathlib.Path)
    ap.add_argument("--profile", required=True,
                    help="basename of the .GYRE file under mesa/LOGS/")
    ap.add_argument("--daughter-band", nargs=2, type=float, metavar=("LO", "HI"),
                    help="parametric daughter band in c/d; default scales the "
                         "dsct_M2.0 band by nu_dyn")
    ap.add_argument("--l-max-core", type=int, default=6)
    ap.add_argument("--l-max-pass1", type=int, default=15)
    ap.add_argument("--l-max-pass2", type=int, default=25)
    ap.add_argument("--force", action="store_true",
                    help="overwrite existing inlists")
    args = ap.parse_args()

    root = args.model_dir
    gyre = root / "gyre"
    gyre.mkdir(parents=True, exist_ok=True)
    # GYRE names these in detail_template but will not create them.
    (gyre / "detail").mkdir(exist_ok=True)
    (gyre / "detail_wide").mkdir(exist_ok=True)
    prof = (root / "mesa" / "LOGS" / args.profile).resolve()
    if not prof.exists():
        raise SystemExit(f"no such profile: {prof}")

    m = read_gyre_model(prof)
    nu_dyn, K = m["nu_dyn"], m["K"]
    scale = nu_dyn / REF_NU_DYN
    band = tuple(args.daughter_band) if args.daughter_band else \
        (REF_BAND[0] * scale, REF_BAND[1] * scale)

    # The 'core' windows scale with nu_dyn off the hand-derived dsct_M2.0 ones
    # (Plans sec 2.1), capped at the acoustic cutoff -- above it there is
    # nothing to find.  At the reference model this reproduces 0.8/25/95
    # exactly, since nu_ac = 94.8 there.  Dnu and nu_ac are reported in the
    # header either way, so a bad window is visible without running GYRE.
    core_lo = REF_SCAN_LO * scale
    split = REF_SPLIT * scale
    p_hi = min(REF_SCAN_HI * scale, 1.02 * m["nu_ac"])
    if p_hi <= split:
        raise SystemExit(f"acoustic cutoff {m['nu_ac']:.1f} c/d is below the "
                         f"p-mode scan split {split:.1f} c/d -- check the model")
    # 'gnet' scan is deliberately wider than the band the n_pg windows encode,
    # so the n_pg limits bind and an error in K cannot silently drop modes.
    g_lo, g_hi = 0.88 * band[0], 1.16 * band[1]

    hdr = HEADER.format(model=root.name, M_msun=m["M"] / 1.988409870698051e33,
                        R_rsun=m["R"] / 6.957e10, nu_dyn=nu_dyn,
                        cut=0.15 * nu_dyn, Dnu=m["Dnu"], nu_ac=m["nu_ac"],
                        I=m["I"], K=K)
    print(f"\n{root.name}:  nu_dyn={nu_dyn:.4f}  Dnu={m['Dnu']:.3f}  "
          f"nu_ac={m['nu_ac']:.1f}  K={K:.3f} c/d")
    print(f"  core scan {core_lo:.2f}-{split:.1f}-{p_hi:.1f} c/d;  "
          f"daughter band {band[0]:.2f}-{band[1]:.2f} c/d"
          f"{'  (scaled)' if not args.daughter_band else '  (given)'}")

    model_blk = (f"\n&model\n  model_type = 'EVOL'\n"
                 f"  file = '../mesa/LOGS/{args.profile}'\n"
                 f"  file_format = 'MESA'\n/\n")
    osc = "\n&osc\n  outer_bound = 'UNNO'\n  variables_set = 'DZIEM'\n{nad}/\n"
    core_scans = (
        f"\n&scan\n  grid_type = 'INVERSE'\n  freq_min = {core_lo:.2f}\n"
        f"  freq_max = {split:.1f}\n  n_freq = 1000\n"
        f"  freq_units = 'CYC_PER_DAY'\n{{tags}}/\n"
        f"\n&scan\n  grid_type = 'LINEAR'\n  freq_min = {split:.1f}\n"
        f"  freq_max = {p_hi:.1f}\n  n_freq = 1000\n"
        f"  freq_units = 'CYC_PER_DAY'\n{{tags}}/\n")

    # ---------------------------------------------------------- narrow run
    narrow_modes = "".join(mode_block(l, -CORE_N_PG, CORE_N_PG, f"l{l}")
                           for l in range(4))
    det_items = ("id,l,m,n_pg,n_p,n_g,omega,freq,x,xi_r,xi_h,eul_Phi,deul_Phi,"
                 "lag_rho,rho,P,Gamma_1,As,c_1,V_2,M_r,M_star,R_star,L_star,E_norm")
    sum_items = ("id,l,m,n_pg,n_p,n_g,omega,freq,E_norm,Delta_p,Delta_g,"
                 "M_star,R_star,L_star")
    grid_core = "\n&grid\n  w_osc = 10\n  w_exp = 2\n  w_ctr = 10\n{tags}/\n"

    write(gyre / "gyre_ad.in", hdr
          + "! Narrow run: l <= 3, |n_pg| <= 20. Eigenfunctions for the coupling tables.\n"
          + "&constants\n/\n" + model_blk + narrow_modes
          + osc.format(nad="") + "\n&rot\n/\n"
          + "\n&num\n  diff_scheme = 'COLLOC_GL4'\n/\n"
          + core_scans.format(tags="") + grid_core.format(tags="")
          + f"\n&ad_output\n  summary_file = 'summary_ad.h5'\n"
            f"  detail_template = 'detail/detail.l%l.n%n.h5'\n"
            f"  summary_item_list = '{sum_items}'\n"
            f"  detail_item_list = '{det_items}'\n"
            f"  freq_units = 'CYC_PER_DAY'\n/\n\n&nad_output\n/\n", args.force)

    write(gyre / "gyre_nad.in", hdr
          + "! Nonadiabatic run for damping rates only: gamma = -Im(omega).\n"
            "! Eigenfunctions come from the adiabatic run, so no detail files here.\n"
          + "&constants\n/\n" + model_blk + narrow_modes
          + osc.format(nad="  nonadiabatic = .TRUE.\n") + "\n&rot\n/\n"
          + "\n&num\n  diff_scheme = 'MAGNUS_GL2'\n  nad_search = 'AD'\n/\n"
          + core_scans.format(tags="") + grid_core.format(tags="")
          + "\n&ad_output\n/\n"
          + f"\n&nad_output\n  summary_file = 'summary_nad.h5'\n"
            f"  summary_item_list = 'id,l,m,n_pg,n_p,n_g,omega,freq,E_norm,"
            f"M_star,R_star,L_star'\n  freq_units = 'CYC_PER_DAY'\n/\n", args.force)

    # ------------------------------------------------------- wide net passes
    gnet_scan = (f"\n! Wider than the {band[0]:.2f}-{band[1]:.2f} c/d band the n_pg limits encode, so the\n"
                 f"! n_pg windows bind and a few percent of error in K cannot silently drop modes.\n"
                 f"&scan\n  grid_type = 'INVERSE'\n  freq_min = {g_lo:.2f}\n"
                 f"  freq_max = {g_hi:.2f}\n  n_freq = 3000\n"
                 f"  freq_units = 'CYC_PER_DAY'\n  tag_list = 'gnet'\n/\n")
    grid_gnet = ("\n&grid\n  w_osc = 15\n  w_exp = 2\n  w_ctr = 10\n"
                 "  tag_list = 'gnet'\n/\n")

    w1 = gnet_windows(K, band, 2, args.l_max_pass1, args.l_max_core, 21)
    w2 = gnet_windows(K, band, args.l_max_pass1 + 1, args.l_max_pass2,
                      args.l_max_core, 21)
    n1 = sum(hi - lo + 1 for lo, hi in w1.values())
    n2 = sum(hi - lo + 1 for lo, hi in w2.values())
    print(f"  gnet pass 1 (l 2-{args.l_max_pass1}): {n1} modes;  "
          f"pass 2 (l {args.l_max_pass1 + 1}-{args.l_max_pass2}): {n2} modes")

    for name, wins, core, summ, note in (
        ("wide", w1, True, "summary_ad_wide.h5",
         f"! Wide daughter net, pass 1 -- l <= {args.l_max_pass1}.\n"),
        ("wide_hi", w2, False, "summary_ad_wide_hi.h5",
         f"! Wide daughter net, pass 2 -- gnet only, l = {args.l_max_pass1 + 1}-{args.l_max_pass2}.\n"),
    ):
        modes = ("".join(mode_block(l, -CORE_N_PG, CORE_N_PG, "core")
                         for l in range(args.l_max_core + 1)) if core else "")
        modes += "".join(mode_block(l, lo, hi, "gnet")
                         for l, (lo, hi) in sorted(wins.items()))
        scans = (core_scans.format(tags="  tag_list = 'core'\n") if core else "") + gnet_scan
        grids = (grid_core.format(tags="  tag_list = 'core'\n") if core else "") + grid_gnet
        det_wide = det_items  # eul_P/lag_P/eul_rho/U already absent: ~30% smaller

        write(gyre / f"gyre_ad_{name}.in", hdr + note + "&constants\n/\n"
              + model_blk + modes + osc.format(nad="") + "\n&rot\n/\n"
              + "\n&num\n  diff_scheme = 'COLLOC_GL4'\n/\n" + scans + grids
              + f"\n&ad_output\n  summary_file = '{summ}'\n"
                f"  detail_template = 'detail_wide/detail.l%l.n%n.h5'\n"
                f"  summary_item_list = '{sum_items}'\n"
                f"  detail_item_list = '{det_wide}'\n"
                f"  freq_units = 'CYC_PER_DAY'\n/\n\n&nad_output\n/\n", args.force)

        write(gyre / f"gyre_nad_{name}.in", hdr + note.replace("--", "-- nonadiabatic,")
              + "&constants\n/\n" + model_blk + modes
              + osc.format(nad="  nonadiabatic = .TRUE.\n") + "\n&rot\n/\n"
              + "\n&num\n  diff_scheme = 'MAGNUS_GL2'\n  nad_search = 'AD'\n/\n"
              + scans + grids + "\n&ad_output\n/\n"
              + f"\n&nad_output\n  summary_file = '{summ.replace('_ad_', '_nad_')}'\n"
                f"  summary_item_list = 'id,l,m,n_pg,n_p,n_g,omega,freq,E_norm,"
                f"M_star,R_star,L_star'\n  freq_units = 'CYC_PER_DAY'\n/\n", args.force)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
